// data.js
export const canciones = [
  {
    id: 1,
    titulo: "Bohemian Rhapsody",
    artista: "Queen",
    album: "A Night at the Opera",
    duracion: 354,
    genero: "Rock",
    año: 1975,
    reproducciones: 0,
  },
  {
    id: 2,
    titulo: "Imagine",
    artista: "John Lennon",
    album: "Imagine",
    duracion: 183,
    genero: "Pop",
    año: 1971,
    reproducciones: 0,
  },
  {
    id: 3,
    titulo: "Stairway to Heaven",
    artista: "Led Zeppelin",
    album: "Led Zeppelin IV",
    duracion: 482,
    genero: "Rock",
    año: 1971,
    reproducciones: 0,
  },
  {
    id: 4,
    titulo: "Smells Like Teen Spirit",
    artista: "Nirvana",
    album: "Nevermind",
    duracion: 301,
    genero: "Grunge",
    año: 1991,
    reproducciones: 0,
  },
  {
    id: 5,
    titulo: "Billie Jean",
    artista: "Michael Jackson",
    album: "Thriller",
    duracion: 294,
    genero: "Pop",
    año: 1982,
    reproducciones: 0,
  },
  {
    id: 6,
    titulo: "Hotel California",
    artista: "Eagles",
    album: "Hotel California",
    duracion: 391,
    genero: "Rock",
    año: 1976,
    reproducciones: 0,
  },
  {
    id: 7,
    titulo: "Sweet Child O' Mine",
    artista: "Guns N' Roses",
    album: "Appetite for Destruction",
    duracion: 356,
    genero: "Rock",
    año: 1987,
    reproducciones: 0,
  },
  {
    id: 8,
    titulo: "Wonderwall",
    artista: "Oasis",
    album: "(What's the Story) Morning Glory?",
    duracion: 258,
    genero: "Rock",
    año: 1995,
    reproducciones: 0,
  },
  {
    id: 9,
    titulo: "Lose Yourself",
    artista: "Eminem",
    album: "8 Mile Soundtrack",
    duracion: 326,
    genero: "Hip-Hop",
    año: 2002,
    reproducciones: 0,
  },
  {
    id: 10,
    titulo: "Rolling in the Deep",
    artista: "Adele",
    album: "21",
    duracion: 228,
    genero: "Pop",
    año: 2010,
    reproducciones: 0,
  },
];
